import dotenv from 'dotenv';
dotenv.config();

const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL || '';

/**
 * Send a message to Slack via Webhook.
 */
export async function sendSlackMessage(text: string): Promise<void> {
    if (!SLACK_WEBHOOK_URL) {
        console.log('[Slack] Skipping send — SLACK_WEBHOOK_URL not configured.');
        return;
    }
    try {
        const res = await fetch(SLACK_WEBHOOK_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ text })
        });
        if (!res.ok) {
            console.warn('[Slack] Webhook failed:', res.status);
        }
    } catch (err: any) {
        console.warn('[Slack] Error:', err.message);
    }
}

/**
 * Generates and sends a Daily Digest to Slack for a user's project.
 */
export async function sendDailyDigest(userId: number, project: string, summary: string) {
    const message = `📅 *Daily Context Brief: ${project}*\n\n${summary}\n\n_Generated by ContextSwitch_`;
    await sendSlackMessage(message);
}
